name: test

on:
  push:
  pull_request:

jobs:

  test_linux:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          sudo git

      - name: generate amalgamation
        run: |
          sudo ./runme.sh

      - name: check generated source
        run: |
          cd /work/gen/
          ls -hal
          ls -al sqlite3.c

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlcipher_amalgamation
          path: /work/gen/*
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "/work/gen/*"
