name: test

on:
  push:
  pull_request:

jobs:

  update-nightly-tag:
    name: Update nightly release tag
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Move nightly tag to head for nightly release
        run: git tag -f nightly && git push origin nightly -f


  test_linux:
    runs-on: ubuntu-22.04
    needs: [update-nightly-tag]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          sudo git

      - name: generate amalgamation
        run: |
          sudo ./runme.sh

      - name: check generated source
        run: |
          pwd
          ls -al
          cd /work/gen/
          ls -hal
          ls -al sqlite3.c
          cp -v /work/gen/* /home/runner/work/gen_sqlcipher_amalgamation/gen_sqlcipher_amalgamation/gen/

      - name: check changes
        run: |
          git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update sqlcipher generated amalgamation
          branch: create-pull-request/sqlcipher-generated-amalgamation
          delete-branch: true
          title: 'update sqlcipher generated amalgamation'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlcipher_amalgamation
          path: /work/gen/*
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "/work/gen/*"
